# Generated by Django 5.1.5 on 2025-01-25 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('weight', models.FloatField()),
                ('height', models.FloatField()),
                ('heartbeat', models.FloatField()),
                ('pressure', models.CharField(max_length=20)),
                ('body_temp', models.FloatField()),
                ('breath_temp', models.FloatField()),
                ('dosage', models.FloatField()),
            ],
        ),
    ]
