# Generated by Django 5.1.5 on 2025-01-25 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dose', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('weight', models.FloatField()),
                ('height', models.FloatField()),
                ('heartbeat', models.IntegerField()),
                ('pressure', models.FloatField()),
                ('body_temp', models.FloatField()),
                ('breath_temp', models.FloatField()),
                ('dosage', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='Patient',
        ),
    ]
