# Generated by Django 5.1.5 on 2025-01-25 12:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dose', '0002_patientrecord_delete_patient'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('weight', models.FloatField()),
                ('height', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='patientrecord',
            name='age',
        ),
        migrations.RemoveField(
            model_name='patientrecord',
            name='height',
        ),
        migrations.RemoveField(
            model_name='patientrecord',
            name='name',
        ),
        migrations.RemoveField(
            model_name='patientrecord',
            name='weight',
        ),
        migrations.AddField(
            model_name='patientrecord',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patientrecord',
            name='heartbeat',
            field=models.FloatField(),
        ),
        migrations.AddField(
            model_name='patientrecord',
            name='patient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='records', to='dose.patient'),
            preserve_default=False,
        ),
    ]
