# Generated by Django 5.1.5 on 2025-01-25 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dose', '0003_patient_remove_patientrecord_age_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='patientrecord',
            name='body_temp',
        ),
        migrations.RemoveField(
            model_name='patientrecord',
            name='breath_temp',
        ),
        migrations.RemoveField(
            model_name='patientrecord',
            name='heartbeat',
        ),
        migrations.RemoveField(
            model_name='patientrecord',
            name='pressure',
        ),
        migrations.AlterField(
            model_name='patient',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='patientrecord',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dose.patient'),
        ),
    ]
