# Generated by Django 5.1.5 on 2025-01-26 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dose', '0005_patient_patient_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientrecord',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='patientrecord',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='patientrecord',
            name='age',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patientrecord',
            name='body_temp',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patientrecord',
            name='breath_temp',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patientrecord',
            name='heartbeat',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patientrecord',
            name='height',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patientrecord',
            name='name',
            field=models.CharField(default='jai', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patientrecord',
            name='pressure',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patientrecord',
            name='weight',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Patient',
        ),
    ]
