# Generated by Django 5.1.5 on 2025-03-02 07:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dose', '0006_remove_patientrecord_patient_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientrecord',
            name='body_temp',
        ),
        migrations.RemoveField(
            model_name='patientrecord',
            name='breath_temp',
        ),
        migrations.RemoveField(
            model_name='patientrecord',
            name='dosage',
        ),
        migrations.RemoveField(
            model_name='patientrecord',
            name='heartbeat',
        ),
        migrations.RemoveField(
            model_name='patientrecord',
            name='height',
        ),
        migrations.RemoveField(
            model_name='patientrecord',
            name='pressure',
        ),
        migrations.RemoveField(
            model_name='patientrecord',
            name='weight',
        ),
        migrations.AddField(
            model_name='patientrecord',
            name='co2_levels',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='patientrecord',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='patientrecord',
            name='heart_rate',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='patientrecord',
            name='respiration_rate',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='patientrecord',
            name='spo2_levels',
            field=models.JSONField(default=list),
        ),
    ]
