# Generated by Django 5.1.5 on 2025-03-02 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dose', '0007_remove_patientrecord_body_temp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientrecord',
            name='code',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
    ]
